### ISSUE TITLE
Enable `fullRehash` of Virtual Maps in `ServicesState#internalInit` after migration to platform-sdk 0.37

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#6037]
### Problem

Currently `ServicesState#internalInit` has the following commented out piece of code:
```
                // FIXME: uncomment after migration to 0.37+
                /*
                if(getChild(StateChildIndices.ACCOUNTS) instanceof VirtualMap accounts) {
                   accounts.fullRehash();
                }
                if(getChild(StateChildIndices.TOKEN_ASSOCIATIONS) instanceof VirtualMap tokenAssociations) {
                    tokenAssociations.fullRehash();
                }
                */
```
It has to be uncommented once the migration to platform-sdk of version 0.37+ happens

Also, [this PR ](https://github.com/hashgraph/hedera-services/pull/5825) renames `internalHashesRamToDiskThreshold` to  `hashesRamToDiskThreshold`  in `JasperDbBuilder`

This issue is a follow up for #5180 

### Solution

Uncomment the code mentioned above

**Comment by imalygin** [comment]
The implementation changed, now `VirtualRootNode` takes care of rehashing of leaves automatically, so the first part about `ServicesState#internalInit` is no longer relevant.

**Comment by imalygin** [comment]
The commit fixing this issue was pushed to `06625-perfnet-testing` branch because this issue resulted in compilation errors in it. Revision number is 31c54405cd519b2562f3253fe447c33d42c40c71
